#+TITLE: dreamforce 2016
#+AUTHOR: natsuki.takeda
#+LANGUAGE: ja
#+OPTIONS: creator:nil LaTeX:t date:t toc:t H:2
#+INFOJS_OPT: view:showall toc:t tdepth:2 ltoc:nil mouse:#ffffcc path:./resource/org-info.js
#+SETUPFILE: ./resource/theme-readtheorg.setup

* Smart Cities Finding Actionable Insights from Big Data
** Overview
*** Description
Join us to learn how Analytics in the cloud are transforming Urban Services, as delivered by both public and private sectors.
クラウドで都市サービスの分析をどうやったんか、公開・非公開で（分析情報を）公開していったんか、（このセッション）に参加して学ぼうや。
*** Speaker
- Ammar Alammar: Practice Senior Director Salesforce
- Dipen Dhruv: Services Sales Director - APAC Salesforce
- Gordon Feller: Cisco Systems HQ - consultant; Meeting of the Minds - founder cisco
** Memo
*** Affordable Digital Infrastructure.
- ストレージ単価は下がり続けてる、Bandwidth も広く安くなった。
*** いろんなデバイスが一つの街の中に沢山、接続してる。急激に広がってる
- 50-75 billion smartboject
- 人口の伸びより遥かに強い勾配で急上昇
*** 新しい essentilal infrastructureが必要なんだ
*** 都市の何を知り（可視化し）、どう解決する？
- 交通量
- 駐車場の問題
	- 駐車場にセンサーとかあるよね
- 都市の諸問題は関連するplayerが多い, 警察とかドライバーとか駐車場オーナーとか
	- ユースケースに応じた
		- ( things  <- sensor -> ) data ---processing---> player のstreamが必要
	- いろいろなthings, そのdata streaming, player use caseごとのprocessing
- 問題の例: boost road capacity and efficency
	- 40%は駐車場を探す人で引き起こされている
	- 1B cars onthe road today 4b -> 2050 $100B + lost in congestion
	- 4B hours of traffic delays ->> loss of $101B inthe us alone
	- traffic -> wasted fuel /greenhouses gasses -> increaded warming -> decline in water
- how
	- visualization realtime traffic, and parking opportunities
	- enhancement reliablity network infra
	- とか
- ゴミ収集車はなんで毎回ちゃんと全部回収できるの？
	- 収集対象（ゴミ箱、色分け、巡回
- 飲料水はなぜきれいに保てるのか
	- sensor, QA
- 都市はtypicalな問題のサイロ
	- digitizing
		-> smart city
		- 現実の例として. barcelona がある [fn:1]
			- smart water/lighting....hospital
- QA
	- Q. コレをやろうとしたら何が必要だ？何をケアしないといけない、
	- A. めっちゃう金かかる。最大のコストセンターはデータセンターになる。
	- Q. ？ （都市間のデータの所有権の問題とかそういう質問があったような。聞き取れず）

** 雑感
- 都市丸ごとなスケールデカイ話を、まともに効果評価しつつ推進するのってどうやんだ
	- 大きい餅を描いてみせたけど、キミはこれをこれからどうすんだっていうのが、よくわからなんだ（あるいは聞き取れなかった）
- このセッション、なんで Dreamforceでやってんだろ。
- システム概要（ユースケース、データの流れっぽいの）のグランドデザインのスライド、高速でページ送りされた。
* Salesforce & Partners, Blazing Trails to Customer Transformation
** Overview
*** Description
The Salesforce partner ecosystem is a powerful force.
Salesforceパートナのエコシステム、つよい。

As the world's largest, and most connected Cloud ecosystem, we come together to drive customer transformation and innovation in whole new ways.
世界でいっちゃんデカイし、色々連携できるクラウドのエコシステムや。新しいいろんな方法をつこうていっしょに顧客の変化・イノベーションをドライブしていこうや。

Join Tyler Prince, EVP, WW Alliances & GTM Innovation and gain insights into partner success, market opportunities and other initiatives that empower Salesforce and partners to continue blazing trails of customer transformation and success.
WW AlliancesとGTM( go-to-market? ) Innovationの EVPのTyler Prince、がパートナーの成功の中から得られた洞察やマーケットのオポチュニティ、その他 継続的な顧客の変化と成功の新機軸を切り開く力先導する要素。（について話す?）
*** Spekaer
- Keith Block: ice Chairman, President & COO Salesforce
- Pam Miller: IDC
- Tyler Prince: Executive Vice President, Channels and GTM Innovation Salesforce
- Adam Seligman: EVP, App Cloud Salesforce
- Todd Surdey: Senior Vice President Salesforce
- Neeracha Taychakhoonavudh: SVP, Partner Programs & Enablement Salesforce
*** Video https://www.salesforce.com/video/282396/
*** Memo what makes our ecosystem amazing
- ohanaspirit
-- parner ecosystm
- innovation
- customer success
*** with keith block
*** tyler
*** with pam miller
ISV, appexchange 貢献してる year over yerar 48%.。成長してる。  eliminates custome questions.
YoY Revenue.
delopment, delveloperの時間も削減してより高サイクルに
*** with todd surdey ISV Sales
isv -> faster easier totime to value
sf(中心にIot) と app
rename app innovation partner
**** adam seligman
- app exchange 広がってる、利用も、高評価なものも
- trust , distribution, innovation
	- Sf自身の全ての機能拡張もこのため
- einstein
	- inteligence smarter
- partner trailblazer
	- faster
		- lightning対応進んでる、appも
		- linghtning certificationを是非。roadmapは引いた
		- winter17
		- component有り物含めてつかえ。 lightnig exchangeをもりあげてくれ
**** joise chase
- app exchange homeを使ってみよ
- sample-usecase: sage live の導入
	- 「ね、簡単でしょ」
	- lightning app builder で d&d customize demop
	- 「ね、簡単でしょ」
- adam seligman
	- もっと作りやすくしていくつもりだからfeed bacck よろ
- Salesforce DX (Deploper experience)
	- source-driven development (apex meta-data)
	- なんか Heroku toolbeltみたいなコマンド体系のCLIデモ
	- git selenium eclipseとかとの統合
*** with wade wegner
- cli development
- json での組織configのpush, cat
	- multicurrencyとかlicenseとか
#+BEGIN_SRC
sfdx force:test
#+END_SRC
- force ideに lightning app builder を統合（ブラウザでガワだしてるだけでは....？）
- jenkins pipelineでbuild test
- inside heroku pipeline
- architectの新しいframework
https://twitter.com/svenkatesan/status/783363089399808000
- partner ohana framework
*** tyler
**** prepackaged- Community & portal with lightning bolt
- neeracha taychakhoonavudh
- デリバリを早く、ラーニングを充実
- parnter community
- trailhead ( one learning dashboard)
- build your buisiness like salesforce
*** 雑感
- chatterに既に流れているので割愛
- salesforce dxはどこまで code で管理できるのか（何ができずに残ってしまうのか）[fn:3]
	- jsonでconfigできるとか、seleniumテスト含めて蹴れるとか胸が熱いのでは
	- demoのときにコンソールにでてた sfdxコマンドのhelp descriptionが Heroku CLIのものだったので、（開発的には）それがベースか。
- lightning experience、app exchangeとあわせて猛push
	- exchange上でappに[LXE ready]とかつけられる。certificationを整えている
* Introduction to Git-Based Continuous Delivery with Heroku Pipelines
** Overview
*** Description
Continuous Delivery is the prescription for code quality, product agility, and engineering velocity.
継続的デリバリはコード品質、プロダクトのアジリティ、開発の速度に寄与する手法や。

In this session, you'll learn how Heroku Flow makes Continuous Delivery simple and flexible.
sこのセッションでは、*Heroku Flow* がCDをごくシンプルに柔軟にしてくれるってところを見せたる。

The Git-based methodology provides for a Pipeline through which code begins as a fully executable pull request, is automatically merged to test and staging apps, and is then deployed to production with a single click.
Gitベースの方法論によって提供される Pipeline機能っちゅうやつは、コードが実行可能なプルリクを起点にして、自動的にテスト・ステージングアプリ環境にマージして(preview appsのこと？)、
そして本番環境へのデプロイまでをワンポチで行えるんや。

Some customers are able to deploy features and fixes up to 500+ times a week, with very few rollbacks from production.
新機能や修正のデプロイを週に500以上もやって、本番環境のごくごく稀なロールバックもやる、そんなことができるお客さんもおるんや。
*** Speaker
- Ike DeLorenzo: Salesforce
- Chris Lonnen: Knight errant mozilla
** Memo
*** CDの定義
*** 何がCDを可能にするのか
- 安くて使い捨てできて、configurableな環境
*** CDにたどり着くまでの歴史
- individual heroics
-- mailでパッチ送り合ってローカルでテストとしてsshでデプロイって世界
- process diagram
-- dev team がvcでcheckin -> build and UT -> auto UAT (smokeテストみたいなんのイメージ？) -> uat -> release
-- jez humble cc by sa 1.0
*** CD On Heroku
- pipelines
- github deploys
- review apps
	- prごとに作られる使い捨て環境
	- (dyno unit の creditの統制効くのかしら？)
- heroku ci
	- まだ beta
	- パット見 werckerの activity みたいな画面がdemoで写ったような
*** Demo
- github画面側へ統合(herokuでのreview app名かつghでのbranch名入れる所ができるx)
- pr作られるとapp-pr名のreview appsが作られる
- prをmergeするとなくなり、mergeされたbase branchでstaging appが再ビルド
- staging appを promote to prod
*** Heroku Flowとは(Demoのまとめ)
*** Heroku Pipelinesの恩恵
- production目線
	- いろいろ
	- 簡易デモとしてのカチを持つ
*** pipelineでできるいろいろ
	- pre-commit checks
	- pre-commit env
	- test
	- Production Traffic Replay（なにこれ？）
	- Multi Environment
*** Mozillaが使ってるよ
** 雑感
- 入りは100人くらい？
- このスピーカーのブログ: Pipeline, Reviewapps, Github syncからなるHeroku flowの話 [[https://blog.heroku.com/heroku_flow_pipelines_review_apps_and_github_sync]]
	- Heroku CIの話はない
	- 対応するdev centerの項はこっち https://devcenter.heroku.com/articles/pipelines
- Heroku ConnectでSF連携が推されていて, Salesforce DXを表に出してきていて、 /テスト環境/ の統合された仕組みか考え方かができるんかいな
* What's Coming from Salesforce and Microsoft
** Overview
*** Description
The Salesforce and Microsoft strategic partnership is ushering in a new era of efficiency and productivity,
SalesforceとMicrosoftの戦略的パートナシップが導く新時代の効率と生産性.

enabling the creation of over ten new and powerful integrations that seamlessly combine the vast resources of Salesforce, the top CRM, and Microsoft Office.
Salesforceと the top CRM とMicrosoft Office の莫大なリソースをシームレスに統合し、10を越える新しくパワフルなインテグレーションを行うことを可能にした。

Join us to learn how BMC Software is leveraging our integrations to work and collaborate with more efficiency and intelligence.
BMC Softwareがこれらのインテグレーションを行うことで可能にした、ごっつ効率的でインテリジェンスな仕事・協調作業を見てってや。
*** Spekaer
- Philippe Marinier: Salesforce
- Daniel Zubkoff: Sr. Director BMC Software
-- これ？ http://www.bmcsoftware.jp/
- 当日いけなかったのでカット
* Salesforce on Salesforce: The Journey to Lightning
** Overview
*** Description
Deploying the Lightning Experience is more than a new skin.
Lightning Experienceは、ただ見た目がオシャンティなだけやないんや。

Lightning is a full scale change to the experience you offer your users on the platform and should be approached as an opportunity to optimize and renew the entire experience.
Lightningはもっとごっつい変化をもたらすんや。あんたんとこのお客さんに最適化した全く新しい体験をしてもらうように是非Lightning Experienceにアプローチすべきやな。

In this session we will share with you how Salesforce planned for this change, the approach we took in prioritizing our use cases and the pathway to deploying this major revision to our own internal user-base.
このセッションではな、Salesforceがこの変更をどうやって計画したんか、ユースケースを優先付けして内部のユーザベースの新しい

This session is an open, honest telling of our own Lightning story from the perspective of our Distribution Business Architect and IT delivery org.
このセッションは、Distribution Business ArchitectとITデリバリ組織の視点から、ごく腹を割って自分らのLightningのストーリーを話すわ。
*** Speaker
- Caroline Hsieh: Salesforce
- Tacy Parker: Director, Go To Market Business Architecture Salesforce
** Memo
*** Mindset
- Lightning is an Experience.
- Countinuous improvement
*** Base the Approach on Persona: For
- Sales team
	- Reps, Ses, Specialists
- business development
	- Console Users
- customer succes
	- Heavy use of custom objectss
*** High Touch
- use caseを見直して以下の様に推進
- Customer facing personasを見直し
- Beta to a team of MPS in Production
*** Low Touch
- Deploy now, adjust later
*** Change Managemnet
we ran communicate makrenign campaign, building anticipation aomng our user as we approached launch.
*** Assesment Approach
*** Enablement Analysis
- Personaごとによく使う機能を整理、プロフファイルを整理
- ex. Account ExecutiveはOpportunity account, Cotanct, Lead, Forecast, Report/Dashboard Chatterをよく使う、Profile:Field Sales/Inside Sales/Product Specialist など
*** Pagelayout optimaization
*** Customization retrofile
*** Winter'17
- 新しい機能はLXEの方でだけ出るんやで。はよLXEしような。
- app manager
- kanban for lead, contracts, campaign
- inline editing in list view(beta)
- vido, image, and code snippet in chatter
*** The sales journey to lightning (まとめ)
*** Lightning STRIKE
- create your lightning story
- assess your readiness
- implment in stages
- keep it simple
- evolve and adapt
** 所感
- 何をいってるのかわからず。英語の問題とLXEのベース知識の問題と
- 参加者 80人くらい？
- LXEを押すぜという強い構えは感じる。
* Japan Customer Summit
** agenda
- facili: nakazawa
- aisatsu: 新役員 miyata
- DF16の参加者について、17万人 japan 500人
** salesforce.comのcustomer jouney
- speaker: michelle mere business process director
- sucess model
	- 5 key lifecycle functions.ステージに依る5つのサポートステージ
us 19万 ( plus 5k/year)
- EWS (early warning system)
	- 組織の利用パターンから手助けがいるんじゃないの？を解析してる
	- そのためのData Scientitsがいる
	- lifecycleを解析して jorneyの framework化をしている
	- lifecycleに併せた補助リソースを整備している（knowledge/base... document/trailheadとか)
- marketing cluodでGetting started以降を追いかけてる/ caseの担当者割当も適切に行うようにしている
- nakazawa: 「ちゃんとメールが送れるように取引先責任者のメンテは気を使ってる
- salescloud - markting cloud
	> infor, health data
	< requests help, mail
  mail開いたhelpみたcase openした・・・追っかけてる
- Roadmap for japanese
- Q. なんでpardotちゃうん？
- A. pardotは小中規模用。データ多いなら markethig cloudのほうが向いている(規模の問題?)
desk.comではpardotというように、セクションによってはSF内でもpardot使ってる。
でも marketing cloudが coreっちゃcore.
- Q. で、効果は
- A. 上がってると思う。データの傾向事実としてモデル化できたユーザ行動の知見はある。この施策単独効果計測したわけではない。
- Q. Getting started/webinarって日本人(user admin)使わないんちゃう？
　　Globalで30%は使ってる。日本人中では50%は使ってる。意味はある。Trailheadについては、あんまデータとってないからヘビーに使ってるとか使ってないとかまではわからん
    ここで喋ってるユーザのユースケースは、adminだけで(developer委託せずに）つかってる例だよ
** HQ 日本職員 panel
- direction: bannai
- panneler:
	- sadahiro suzuki (ntt software as user position)
	- ryuji osawa
		- wave analytics dashboard/explore
	- yuri sebata-dember
		- designer (communityX cloud lightning template)
	- daisuke kawamoto
		- infra performance
	- junichiro sekiguchi
		- Database
	- kumiko jacobs
		- localization pm
- Q. 最近にAP障害多くない?
- A. SF trustsの"障害"閾値はかなり低い
	障害になってもユーザからケースが上がらないことがかなり多い
	sandoboxがやばいのは頑張って対応してる
	(話がすり替わった?)
- trailhead badgeの日本語化進めてる
- idea exchange高評価もっと採用してほしい...
	評価は注目している。高評価=採用ではない
- 「engeneering側が拒否することもあるんだよ。思われてるほどProduct Managerは強くないんだよ」
** ここで、体調不良でJapan Cutomer Summitは中座
** NTT Software dreamforce: suzuki sadahiro
** App Excahnge@dreamforce expo: kitahara yuji
* Building Heroku + Force.com Architectures to Extend Your Salesforce Deployment
** Overview
*** Description
Our Trailblazers build amazing things with the App Cloud.
やり手や奴らはApp Cloudをつこうてものすんごいもんを作りおる。

With over 15 million custom apps developed on App Cloud, developers occasionally run into a requirements that seem impossible to solve with Force.com alone.
1500万を越えるアプリがApp Cloudの上で作られとって、開発者はForce.comだけではちょっとやりようがあらへん要件を実現したりしとる。

Very often, Heroku is the solution.
Herokuもよう選ばれる解決策や。

In this session we will describe real world architecture patterns and show how App Cloud (Heroku + Force.com together) provide robust and scalable solutions for the patterns.
このセッションでは、実際に使われとるアーキテクチャパターンとか、 App Cloudで(HerokuとForce.comを使って）耐久性に優れたスケーラブルなもんを作る方法について紹介するわ。
*** Speaker
- Dan Mehlman: Salesforce Heroku Technical Architect @DanTheCloudGuy
- Gopal Patel: CTO GetFeedback
- Peter Shankar: Chief Technology Officer Equity Multiple
*** Memo
**** platform roles
- Functional apps
- model-driven apps: force.com
- webscale apps heroku
*** usecase
- apis and micor services on heroku(include heroku connect): elastic compute
- data warehousing and data integration, secured. private spaces, postgres, connect
- streaming, iot: xively...
*** getfeedbackのヒトから cx について
- modern, mobile ready, high responseが求められてるよ
- feeedback は 簡単にくるけど、相手のstage(journey)こみで解釈しないとね
**** [[getthefeedback][https://www.getfeedback.com/]] の demo
- getthefeedbackでアンケート作って配信して、ユーザがresposiveでhigh responseなとフィードバック画面から送信して、即SFに反映されるまで
*** mission capital: dataware housing, augomented salesforce
- 何をしようとした？
	- ローンの問題に関する金融サービスを扱う。いろんな金融商品、いろんなサービスが絡む。
	- loan buyer/seller、雇用者向け向け
- challenge
	- dilligence ds(外部データいっぱい使う)
	- ややこいreport,がいる(complex join), PDFで
	- ストレージ最適かしないと(SFでdatawarehouseとか、やばいやん？）
- solution
	- 結局herokuでwarehouse
	- 機能分割してmicro service
	- 分割したsf組織とheroku api/app/reportingの組み合わ絵sで
	- tradesupport org, dilligence org 1,2,...n
	- org と appsをheroku connectでつなぐ
*** data archive
- 組織が育ってデータが増えて sf orgの制限に引っかかった場合に
	- 安全に(complianceとか)
	- 検索可能性を保ったまま
	- 経済的に
	- よそにデータをうつす
*** QA
- Q.データはわかった。metadataはどうする？
- A.
- Q. Heroku Connect高いけど何がいいの？
- A. ApexとかStreamAPIでもできるけど、やっぱシンプルだよ
- Q. User authenticationはどうしてる？（って言ってた気がする）
**** later
- mission capital.com: demoしてたアプリ
- mailtrap: メール送信demoでつかってた模様。SMTPのプロキシとして振る舞って、実際の送信先とは違うところに送る模様。、 [[https://mailtrap.io/]] ユーザデータみたいなんでテストするときに送信先を開発者アカウントに捻じ曲げるためにつかう？
* Migrating Lightning Components from Visualforce
** Overview
*** Description
You have an investment in Visualforce Pages but you are ready to make the move to Lightning Components.
VF Pageはもう詳しいと思うけど、せやけど Lightning Componentsに移行する準備が必要や。

You could rebuild every page from scratch but converting seems like a better idea,
but what kind of strategies and tactics make for a successful conversion? In this session we will illustrate different strategies and tactics,
using real world examples on migrating to Lightning Components from Visualforce Pages.
*** Speaker
- Chen Deng: Salesforce
- Anas Jadallah: Salesforce
- Anastasia Shpurik: Anastasia Shpurik
** Memo
- Visualforce vs lightning component
	- vf: htmlとviewstateで. server rendering. page base.
	- lightning:  client appとjson, client rendering. app base.
- roadmap
	- plan: page base -> app base の設計変更から何が再利用できるか考えような。
	- dev
		- Lightning Component Builderがくるで
		- VFが埋め込めんこともないで. ref. lightning out まだ beta ( [[https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/lightning_out.htm]] 一旦外に通信に行くってこと？)
		- component 1-* standard controller - shared cache - server
	- test
		- component の unit testing framework, runner dashboard な UI. coming soonでござい
	- launch
		- fallback to visualforce using multiple layouts
- demo
	- vf pageのソースをちょろまかして lightning componentsに仕立てて表示
	- quick actionsを作って配置して、modal dialogに仕立てる
	- 単独ページでも同じcomponentを配置。どや、reuseやろ。
** 所感
- 新しい話が多いわけでもない気がするわりに、意外に人多くて. 列が長い。
- タイトルキーワードに引っかかる人が多いのか、でも離席が多い.

* "Be a Customer Trailblazer" with Marc Benioff & Special Guests
** Overview
*** Description
Join Marc Benioff and industry giants to see the future of customer engagement.
Marc will highlight how innovative companies are using the cloud, mobility, IoT and artificial intelligence to achieve new levels of success with connecting with their customers.
Salesforce will showcase new products and technology like Einstein that will dramatically change how employees across sales, service, marketing & IT perform their jobs and engage with customers.
Seating in the Main Keynote is limited. Attendees will be seated first-come, first-served. The keynote will be broadcast at locations throughout the Dreamforce Campus.
** Memo
- - 13:00 スポンサーインタビュー. accentureとかcocacolaとか。
- - 13:15 なんだっけ。
- - 13:25 "ohana" を受けての aloha takaの音楽セッション
- - 13:27 SFのPV.  einstein trail ohana推し
- 13:29 - Marc benioff登場
	- "thanks community"
	- SFの成長の話 forbes, fortuneへの掲載を出しながら
	- 1-1-1の話 : the age of equality
		- 具体的な援助のはなし 主に教育援助
	- a smarter world (roadmap, connected , iot -> ai -> )
	- the age of the customer 顧客接点サービスの増加変化
		- ex. turbo tax, asics, uber,
	- "no codeで素早くやりたいことがやれるplatformを広く"
	- ということでAI: SFのベースに組み込まれていく機能
		- -> einstein
	- lightning family
		- サービス発展ののagilityのために必要なもの
		- showcaseとしてはquip
	- enterprise 5角変革と対応するSF製品/サービス
		- 紹介
		- unity ecommerce
		- mobile salesforce1
		- などなどplatformとしてappが揃ってきた
	- einstein by parker parris
		- 技術や理屈がやや小難しいAIについて、AIを使うユースケースの土台を作っておいて、シンプルに使えるようにする
		- arch. layer: secureなdata層(thnder)と接点apps(lightning)の間に einsteinが位置する
	- shuba nabbar ( einstein 紹介)
		- データソースの統合、スクラッチ開発なしに
		- uc1. 競合の分析とtodo recommend ( snsなど外部ソースも含め分析対象に含める )
		- uc2. ケースの重要度をスコアリングして一覧に表示、フィルタ（全部見られて探せるのではなく、必要な情報を必要な情報にサジェストする。思想としては、ubiquitousからambientへ、のくだりで7年前にも聞いた気がするけど。）
			- スコアリングのフローを設定するビルダー画面もあります
	- lightningを改めてharrisから押し 「SFとしてはLightningはreadyなんだ、使える状態になったんだ」
	- 14:10- 14:35 red, ebony frelix
		- sf1, com cloud on thnder bolt (pow by einstein) demo
		- ceoa
	- 14:36 - 14:54- schnide electric: pv integrate subsystem, iot, einstein. mobile by alex dayon
		- Salesforce CPQ
			- lead concatc 管理、見積もり
		- filed service einstein
		- my salesforce 1
	- 14:55 -   fitbit by stephany buscemi
** 雑感
- Lightning推してくる
	- 今日までの間、Classic画面をほとんど見ていない。Classic禁止令でも出てるのか。世間はClassicなんか使ってないのか
	- Einsteinが基盤的な存在として遍在することになる、というのが個人的には印象的
- CSRアピール枠、結構しっかりとってくるものなのね
- DXな話は、この基調講演には入らない
* Deep Dive into the New Salesforce Development Experience (DX) Architecture
** Overview
*** Description
The new Developer Experience for Force.com developers required a new way to think about development on the Platform.
Force.com開発者のための新しいDeveloper Experienceとして、プラットフォーム上での開発の新しい手法が求められとる。

Join us as we discuss the architectural changes within the Force.com Platform to support the new Developer Experience.
Foce.comプラットフォームのアーキテクチャレベルの変更、新しいDXのサポートについて話す。

Find out what is being changed within the Platform and what is being developed on the client.
何が変わっていくのか、何を作っていくのか。

This is a technical session covering a new way to think about development orgs, source change tracking, team development, test running and other exciting upcoming features.
開発組織、コード変更の追跡、チーム開発、テスト実行、とかとか。

* Building Force.com Apps from Source
** Overview
*** Description
Learn about the new features being built out in within the AppCloud Developer Experience.
AppCloud Develoepr Experienceの新しい機能について。

In this session, we will discuss the App Cloud CLI Plugin, Workspace Orgs for development and testing, as well as our Source Synchronization commands to help you better interact with an org and more easily integrate with source control systems.
App Cloud CLI Plugin, 開発・テストのための組織のワークスペース, ソースの動機コマンドで組織の操作を簡単にソース管理システムとの統合をより簡単に。
** memo
- pricinples of modern software delivery
	- (色々書いてあったけど) CI/CD, Github flow的な, リッチなtask runnerとかそういうの、やるやろ？やりたいやろ？
- SFはどう変わる?
	- runtimeじゃない、VCSとして : sourt of truth
	- environmentsもいっぱい作れるように...とか
	- 世のPrinciplesに寄っていくようになる
- Salesforce DX
	- Sourceとは以下の要素を含むようになる
		- app code
		- metadate
		- org confi
	- Salesfoce DX APIs
		- ツールから叩ける用にな
		- ソースの動機、変更のトラッキング
		- とかとかするので、
			- 今のよくあるやり方で統制を効かせられるようになるんや
	- Salesforce CLI
		- CI/DEV用組織作ったり、組織とローカルのソース動悸したり、データ同期（開発・テスト用途で）したり・・・
	- Salesforce IDE
		- eclipseベース
		- Code Completion や Refactoringにも対応する
	- Scratch Orgs
		- 使い捨て組織を作れるように、DEV/CI用途
	- Pipelines
		- Herokuのそれみたいなの Review appsとか
	- Heroku CI
		- Support for apex and mixed language apps
	- packaging 2.0
		- multiple package from a single namespace
- demo
	- scratch orgで開発用組織作って
	- 他の組織からsource同期してきて
	- ローカルで編集して
	- 開発用組織にpushして、さっき編集したファイルが同期される
- dev -> prd リリース
	- diffのchange setをprdに送りつける
	- vcsのリリースブランチから組織に同期される
	- 違うパッケージがそれぞれあるブランチ複数から1つの組織へ同期
	- 複数のappから組織を構成するという考え方/設計が可能に
- sandbox
- QA
** 所感
- 80人くらい？

- 途中離脱する人多い 5,6人くらい？
- speakerのおっさん舌打ち多め
* How Salesforce Builds Salesforce using Heroku
** Overview
*** Description
Attend this session and learn how Salesforce development teams build amazing apps using Heroku for greater agility while maintaining the highest level of trust.
Herokuでアジリティと信頼性の高い、アプリの作りかたを。

We use Heroku for internal apps like our Concierge IT portal, external apps like Trailhead, and secure data synchronization between internal Salesforce orgs.
Herokuを使った、内部向けの気の利いたポータルとか、Trailheadみたいな外向けアプリとか、セキュアなデータをSF組織と動機するようなんとか。

You’ll see how we use Heroku to build apps that provide a unified user experience and presentation layer across multiple different Salesforce orgs.
複数の異なったSF組織を跨いだプレゼンテーションレイヤ・統合されたUXを提供するアプリをHerokuで。

* Salesforce for Marketing Keynote: The Smartest CRM for 1-to-1 Customer Journeys
** Overview
*** Description
Marketing is the sum of all interactions with your brand.
In a world where customer experience is king, relevant and contextual interactions are the keys to the kingdom.
Join Bryan Wade, CPO & SVP of Marketing Cloud, and special guests to discover an evolution in marketing that puts the customer at the center of every experience with your brand -- from awareness and acquisition, to retention. Hear how the world's most innovative companies, including Change.org, MasterCard, and Dunkin' Brands, are getting smarter and more predictive about their customers, creating seamless 1-to-1 customer journeys.
* Salesforce for Developers Keynote
** Overview
*** Description
Apps have never been more critical in our lives and our work, and everything and everyone is connected.
This app revolution has given rise to a global renaissance for developers.
At the same time, our digital experiences are often disconnected and new apps frequently lag expectations.
Join Srini Tallapragada, President, Technology at Salesforce, in this year's Developer Keynote, to learn how to build apps faster, smarter and for the future, today.
* Salesforce Einstein Keynote: AI for Everyone
** Overview
*** Description
AI is the next great technology disruption transforming how we live and work, and Salesforce Einstein is the first comprehensive AI platform for CRM. Join John Ball, GM of Salesforce Einstein, along with some of Salesforce's most innovative customers, to see how they're getting smarter and more predictive about their customers.
* Continuous Delivery from Dev to Production with Heroku Flow
** Overview
*** Description
Delivering software in small batches in a continuous manner drastically reduces risk and is one of the core tenets of Agile methodology. Continuous Delivery (CD) takes a disciplined approach to building software, where it's releasable to production at any time. Join us to see how Heroku Flow embeds CD right into the platform, making it easy for teams to iterate rapidly on apps and features customers care about.
* Salesforce for Admins Keynote
** Overview
*** Description
Every day is an adventure when you're a Salesforce Administrator. You spend your days in the cloud and on the ground in a quest to become more efficient and more effective. You're passionate about productivity and using innovative technology to create positive and lasting impact for your customers, your company and the community. Join Mike Rosenbaum, EVP CRM Applications, Kris Lande, Sr. Director Admin Marketing and Mike Gerholdt, Sr. Manager Admin Evangelism on an adventure with fellow Trailblazers as we discover new ways to use technology to go faster, get smarter and go further.
* Build Sophisticated App Configurations with Custom Metadata
** Overview
*** Description
At Dreamforce last year we launched custom metadata types. This year we add a heavily requested, powerful new capability: metadata relationships. You can now build complex, hierarchical metadata structures by relating your custom metadata to other custom metadata and even to standard and custom objects and fields! If you are still using custom settings or custom objects for app configurations, attend this session to learn how custom metadata types can save your time and sanity managing app configurations and eliminate the need for sophisticated custom tooling or manual configuration and deployment processes.
* Template Title
** Overview
*** Description
*** Spekaer
- hoge
- fuga

[fn:1] バルセロナスマートシティ話は この辺 http://smartcity.bcn.cat/en/buits-plan.html 分析プラットフォームはAzureとかPower BI https://azure.microsoft.com/en-us/documentation/videos/windows-azure-case-study-barcelona-bigdata/ ?
[fn:2] https://www.salesforce.com/video/282396/
[fn:3] https://www.salesforce.com/products/platform/products/salesforce-dx/ ブースの salesforce DXのエリアは(developerぽい)人がタカってた
