#+TITLE: dreamforce 2016
#+AUTHOR: natsuki.takeda
#+LANGUAGE: ja
#+OPTIONS: creator:nil LaTeX:t date:t toc:t H:2
#+INFOJS_OPT: view:showall toc:t tdepth:2 ltoc:nil mouse:#ffffcc path:./resource/org-info.js
#+SETUPFILE: ./resource/theme-readtheorg.setup

* Smart Cities Finding Actionable Insights from Big Data
** Overview
*** Description
Join us to learn how Analytics in the cloud are transforming Urban Services, as delivered by both public and private sectors.
クラウドで都市サービスの分析をどうやったんか、公開・非公開で（分析情報を）公開していったんか、（このセッション）に参加して学ぼうや。
*** Speaker
- Ammar Alammar: Practice Senior Director Salesforce
- Dipen Dhruv: Services Sales Director - APAC Salesforce
- Gordon Feller: Cisco Systems HQ - consultant; Meeting of the Minds - founder cisco
** Memo
*** Affordable Digitail Infrastructure. 
ストレージ単価は下がり続けてる、Bandwidth も広く安く
*** いろんなデバイスが一つの街に沢山、接続してる。急激に広がってる
50-75 billion smartbojects、人口に対して急増
*** 新しい essentilal infrastructureが必要あね　
*** 都市の何を知りどう解決する？
- 交通量
- 駐車場の問題
- iotで？parking spaceにsensor.
- playerが多い, polici, driver, owner...
	- data -> <processing> -> people
	- いろいろなthings, そのdata streaming, player use caseごとのprocessing
- boost road capacity and efficency
	- 40%は駐車場を探す人で引き起こされている
	- 1 b cars onthe road today 4b -> 2050 $100B + lost in congestion
	- 4.B hours of traffic delays ->> loss of $101B inthe us alone
	- traffic -> wasted fuel /greenhouses gasses -> increaded warming -> decline in water
- how
	- visualization realtime traffic, and parking opportunities
	- enhancement reliablity network infra
	-
- ゴミ収集車はなんでちゃんと全部改修できるの？
	- 収集対象（ゴミ箱、色分け、巡回
- 飲料水はなぜきれいに保てるのか
	- sensor, QA
- 都市はtypicalな問題のサイロ
	- digitizing
		-> smart city
		- real ex. barcelona
			- smart water/lighting....hospital
- QA
-- Q. コレを広めようとしたら何が必要だ？何をケアしないといけない、
-- A. めっちゃうかねはかかる。コストセンターはデータセンターになる。
-- Q. 聞き取れないけど絵に描いた餅感がある的なはなし？
-- Q. 都市間のデータの所有権とかそういう話？
-- A. 
* Salesforce & Partners, Blazing Trails to Customer Transformation
** Overview
*** Description
The Salesforce partner ecosystem is a powerful force.
Salesforceパートナのエコシステム、つよい。

As the world's largest, and most connected Cloud ecosystem, we come together to drive customer transformation and innovation in whole new ways.
世界でいっちゃんデカイし、色々連携できるクラウドのエコシステムや。新しいいろんな方法をつこうていっしょに顧客の変化・イノベーションをドライブしていこうや。

Join Tyler Prince, EVP, WW Alliances & GTM Innovation and gain insights into partner success, market opportunities and other initiatives that empower Salesforce and partners to continue blazing trails of customer transformation and success.
WW AlliancesとGTM( go-to-market? ) Innovationの EVPのTyler Prince、がパートナーの成功の中から得られた洞察やマーケットのオポチュニティ、その他 継続的な顧客の変化と成功の新機軸を切り開く力先導する要素。（について話す?）

*** Spekaer
- Keith Block: ice Chairman, President & COO Salesforce
- Pam Miller: IDC
- Tyler Prince: Executive Vice President, Channels and GTM Innovation Salesforce
- Adam Seligman: EVP, App Cloud Salesforce
- Todd Surdey: Senior Vice President Salesforce
- Neeracha Taychakhoonavudh: SVP, Partner Programs & Enablement Salesforce
*** typer
**** what makes our ecosystem amazing
- ohanaspirit
-- parner ecosystm
- innovation
- customer success
*** with keith block
*** tyler
*** with pam miller
ISV, appexchange 貢献してる year over yerar 48%.。成長してる。  eliminates custome questions.
YoY Revenue.
delopment, delveloperの時間も削減してより高サイクルに
*** with todd surdey ISV Sales
isv -> faster easier totime to value
sf(中心にIot) と app
rename app innovation partner
**** adam seligman
- app exchange 広がってる、利用も、高評価なものも
- trust , distribution, innovation
-- Sf自身の全ての機能拡張もこのため
- einstein
-- intteligence smarter
- partner trailblazer
-- faster
--- lightning対応進んでる、appも
--- linghtning certificationを是非。roadmapは引いた
--- winter17
--- component有り物含めてつかえ。 lightnig exchangeをもりあげてくれ
**** joise chase
---- app exchange homeを使ってみよ
---- sample-usecase: sage live
---- 「ね、簡単でしょ」
---- lightning app builder で d&d customize demop
---- 「ね、簡単でしょ」
-- adam seligman
--- もっと作りやすくしていくつもりだからfeed bacck よろ
-- Salesforce DX (Deploper experience)
--- source-driven development (apex meta-data)
--- なんか Heroku toolbeltみたいなデモ
--- git selenium eclipseとかとの統合
--- git flowもいしきしてるっぽい
*** with wade wegner
- forcedotcom/dreamhouse-partnerkeynote-sdx
- cli development
- json でのconfigのpush, cat
```
sfdc force:test
```
- force ideに lightning app builder を統合（ブラウザでガワだしてるだけでは....？）
- jenkins pipelineでbuild test
- inside heroku pipeline
- architectの新しいframework
https://twitter.com/svenkatesan/status/783363089399808000
- partner ohana framework
*** tyler
**** prepackaged- Community & portal with lightning bolt
- neeracha taychakhoonavudh
- デリバリを早く、ラーニングを充実
- parnter community
- trailhead ( one learning dashboard)
- build your buisiness like salesforce
* Introduction to Git-Based Continuous Delivery with Heroku Pipelines
** Overview
*** Description
Continuous Delivery is the prescription for code quality, product agility, and engineering velocity.
継続的デリバリはコード品質、プロダクトのアジリティ、開発の速度に寄与する手法や。

In this session, you'll learn how Heroku Flow makes Continuous Delivery simple and flexible.
sこのセッションでは、*Heroku Flow* がCDをごくシンプルに柔軟にしてくれるってところを見せたる。

The Git-based methodology provides for a Pipeline through which code begins as a fully executable pull request, is automatically merged to test and staging apps, and is then deployed to production with a single click.
Gitベースの方法論によって提供される Pipeline機能っちゅうやつは、コードが実行可能なプルリクを起点にして、自動的にテスト・ステージングアプリ環境にマージして(preview appsのこと？)、
そして本番環境へのデプロイまでをワンポチで行えるんや。

Some customers are able to deploy features and fixes up to 500+ times a week, with very few rollbacks from production.
新機能や修正のデプロイを週に500以上もやって、本番環境のごくごく稀なロールバックもやる、そんなことができるお客さんもおるんや。
*** Speaker
- Ike DeLorenzo: Salesforce
- Chris Lonnen: Knight errant mozilla
** Memo
*** 入りは100人くらい？
*** CDって？
*** 何がCDを可能にするのか
安くて使い捨てできて、configurableな環境
*** CDにたどり着くまでの歴史
- individual heroics
-- mailでパッチ送り合ってローカルでストとしてsshでデプロイい
- process diagram
-- dev team vc build/ut auto accpetance test(smoke?), uat release
-- jez humble cc by sa 1.0
*** CD On Heroku
- pipelines
- github deploys
- review apps
-- prごとに作られる使い捨て環境
-- (creditの統制効くのか・・・？)
- heroku ci
-- まだ beta
*** Demo
- github画面側へ統合(herokuでのreview app名かつghでのbranch名入れる所ができるx)
- pr作られるとapp-pr名のreview appsが作られる
- prをmergeするとなくなり、mergeされたbase branchでstaging appが再ビルド
- staging appを promote to prod
*** Heroku Flowとは(Demoのまとめ)
*** Heroku Pipelinesの恩恵
- production目線
-- いろいろ
-- 簡易デモとしてのカチを持つ
- development目線
- pipelineでできるいろいろ
-- pre-commit checks
-- pre-commit env
-- test
-- *Production Traffic Replay*
-- *Multi Environment*
*** Mozillaが使ってるよ
* What's Coming from Salesforce and Microsoft
** Overview
*** Description
The Salesforce and Microsoft strategic partnership is ushering in a new era of efficiency and productivity,
SalesforceとMicrosoftの戦略的パートナシップが導く新時代の効率と生産性.

enabling the creation of over ten new and powerful integrations that seamlessly combine the vast resources of Salesforce, the top CRM, and Microsoft Office.
Salesforceと the top CRM とMicrosoft Office の莫大なリソースをシームレスに統合し、10を越える新しくパワフルなインテグレーションを行うことを可能にした。

Join us to learn how BMC Software is leveraging our integrations to work and collaborate with more efficiency and intelligence.
BMC Softwareがこれらのインテグレーションを行うことで可能にした、ごっつ効率的でインテリジェンスな仕事・協調作業を見てってや。
*** Spekaer
- Philippe Marinier: Salesforce
- Daniel Zubkoff: Sr. Director BMC Software
-- これ？ http://www.bmcsoftware.jp/

* Salesforce on Salesforce: The Journey to Lightning
** Overview
*** Description
Deploying the Lightning Experience is more than a new skin.
Lightning Experienceは、ただ見た目がオシャンティなだけやないんや。

Lightning is a full scale change to the experience you offer your users on the platform and should be approached as an opportunity to optimize and renew the entire experience.
Lightningはもっとごっつい変化をもたらすんや。あんたんとこのお客さんに最適化した全く新しい体験をしてもらうように是非Lightning Experienceにアプローチすべきやな。

In this session we will share with you how Salesforce planned for this change, the approach we took in prioritizing our use cases and the pathway to deploying this major revision to our own internal user-base.
このセッションではな、Salesforceがこの変更をどうやって計画したんか、ユースケースを優先付けして内部のユーザベースの新しい

This session is an open, honest telling of our own Lightning story from the perspective of our Distribution Business Architect and IT delivery org.
このセッションは、Distribution Business ArchitectとITデリバリ組織の視点から、ごく腹を割って自分らのLightningのストーリーを話すわ。
*** Speaker
-- Caroline Hsieh: Salesforce
-- Tacy Parker: Director, Go To Market Business Architecture Salesforce
** Memo
*** Mindset
- Lightning is an Experience.
- Countinuous improvement
*** Base the Approach on Persona: For
- Sales team
	- Reps, Ses, Specialists
- business development
	- Console Users
- customer succes
	- Heavy use of custom objectss
*** High ouch
- use caseを見直して以下の様に推進
- Customer facing personasを見直し
- Beta to a team of MPS in Production
*** Low Touch
- Deploy now, adjust later

*** Change Managemnet
we ran communicate makrenign campaign, building anticipation aomng our user as we approached launch.
*** Assesment Approach
*** Enablement Analysis
Personaごとによく使う機能を整理、プロフファイルを整理
- ex. Account ExecutiveはOpportunity account, Cotanct, Lead, Forecast, Report/Dashboard Chatterをよく使う、Profile:Field Sales/Inside Sales/Product Specialist など
*** Pagelayout optimaization
*** Customization retrofile
*** Winter'17
- 新しい機能はLXEの方でだけ出るんだぜ
- app manager
- kanban for lead, contracts, campaign
- inline editing in list view(beta)
- vido, image, and code snippet in chatter
*** The sales journey to lightning (まとめ)
** memo
まぁ、色々いってLightningを押すぜという強い構え
* Building Heroku + Force.com Architectures to Extend Your Salesforce Deployment
** Overview
*** Description
Our Trailblazers build amazing things with the App Cloud.
App Cloudをつこうてものすんごいもんを作りおる。

With over 15 million custom apps developed on App Cloud, developers occasionally run into a requirements that seem impossible to solve with Force.com alone.
1500万を越えるアプリがApp Cloudの上で作られとって、開発者はForce.comだけではちょっと実現が難しいような要件を実現したりしとる。

Very often, Heroku is the solution.
Herokuもよく選ばれる解決策や。

In this session we will describe real world architecture patterns and show how App Cloud (Heroku + Force.com together) provide robust and scalable solutions for the patterns.
このセッションでは、実際に使われとるアーキテクチャパターンとか、 App Cloudで(HerokuとForce.comを使って）耐久性に優れたスケーラブルなもんを作る方法について紹介するわ。
*** Speaker
- Dan Mehlman: Salesforce
- Gopal Patel: CTO GetFeedback
- Peter Shankar: Chief Technology Officer Equity Multiple
* "Be a Customer Trailblazer" with Marc Benioff & Special Guests
** Overview
*** Description
Join Marc Benioff and industry giants to see the future of customer engagement.
Marc will highlight how innovative companies are using the cloud, mobility, IoT and artificial intelligence to achieve new levels of success with connecting with their customers.
Salesforce will showcase new products and technology like Einstein that will dramatically change how employees across sales, service, marketing & IT perform their jobs and engage with customers.
Seating in the Main Keynote is limited. Attendees will be seated first-come, first-served. The keynote will be broadcast at locations throughout the Dreamforce Campus.

クラウド、動体、IoT、人工知能に注目。新しい製品・技術のショーケース。Einstein。

* Deep Dive into the New Salesforce Development Experience (DX) Architecture
** Overview
*** Description
The new Developer Experience for Force.com developers required a new way to think about development on the Platform.
Force.com開発者のための新しいDeveloper Experienceとして、プラットフォーム上での開発の新しい手法が求められとる。

Join us as we discuss the architectural changes within the Force.com Platform to support the new Developer Experience.
Foce.comプラットフォームのアーキテクチャレベルの変更、新しいDXのサポートについて話す。

Find out what is being changed within the Platform and what is being developed on the client.
何が変わっていくのか、何を作っていくのか。

This is a technical session covering a new way to think about development orgs, source change tracking, team development, test running and other exciting upcoming features.
開発組織、コード変更の追跡、チーム開発、テスト実行、とかとか。

* Building Force.com Apps from Source
** Overview
*** Description
Learn about the new features being built out in within the AppCloud Developer Experience.
AppCloud Develoepr Experienceの新しい機能について。

In this session, we will discuss the App Cloud CLI Plugin, Workspace Orgs for development and testing, as well as our Source Synchronization commands to help you better interact with an org and more easily integrate with source control systems.
App Cloud CLI Plugin, 開発・テストのための組織のワークスペース, ソースの動機コマンドで組織の操作を簡単にソース管理システムとの統合をより簡単に。

* How Salesforce Builds Salesforce using Heroku
** Overview
*** Description
Attend this session and learn how Salesforce development teams build amazing apps using Heroku for greater agility while maintaining the highest level of trust.
Herokuでアジリティと信頼性の高い、アプリの作りかたを。

We use Heroku for internal apps like our Concierge IT portal, external apps like Trailhead, and secure data synchronization between internal Salesforce orgs.
Herokuを使った、内部向けの気の利いたポータルとか、Trailheadみたいな外向けアプリとか、セキュアなデータをSF組織と動機するようなんとか。

You’ll see how we use Heroku to build apps that provide a unified user experience and presentation layer across multiple different Salesforce orgs.
複数の異なったSF組織を跨いだプレゼンテーションレイヤ・統合されたUXを提供するアプリをHerokuで。

* Salesforce for Marketing Keynote: The Smartest CRM for 1-to-1 Customer Journeys
** Overview
*** Description
Marketing is the sum of all interactions with your brand.
In a world where customer experience is king, relevant and contextual interactions are the keys to the kingdom.
Join Bryan Wade, CPO & SVP of Marketing Cloud, and special guests to discover an evolution in marketing that puts the customer at the center of every experience with your brand -- from awareness and acquisition, to retention. Hear how the world's most innovative companies, including Change.org, MasterCard, and Dunkin' Brands, are getting smarter and more predictive about their customers, creating seamless 1-to-1 customer journeys.
* Salesforce for Developers Keynote
** Overview
*** Description
Apps have never been more critical in our lives and our work, and everything and everyone is connected.
This app revolution has given rise to a global renaissance for developers.
At the same time, our digital experiences are often disconnected and new apps frequently lag expectations.
Join Srini Tallapragada, President, Technology at Salesforce, in this year's Developer Keynote, to learn how to build apps faster, smarter and for the future, today.
* Salesforce Einstein Keynote: AI for Everyone
** Overview
*** Description
AI is the next great technology disruption transforming how we live and work, and Salesforce Einstein is the first comprehensive AI platform for CRM. Join John Ball, GM of Salesforce Einstein, along with some of Salesforce's most innovative customers, to see how they're getting smarter and more predictive about their customers.
* Continuous Delivery from Dev to Production with Heroku Flow
** Overview
*** Description
Delivering software in small batches in a continuous manner drastically reduces risk and is one of the core tenets of Agile methodology. Continuous Delivery (CD) takes a disciplined approach to building software, where it's releasable to production at any time. Join us to see how Heroku Flow embeds CD right into the platform, making it easy for teams to iterate rapidly on apps and features customers care about.
* Salesforce for Admins Keynote
** Overview
*** Description
Every day is an adventure when you're a Salesforce Administrator. You spend your days in the cloud and on the ground in a quest to become more efficient and more effective. You're passionate about productivity and using innovative technology to create positive and lasting impact for your customers, your company and the community. Join Mike Rosenbaum, EVP CRM Applications, Kris Lande, Sr. Director Admin Marketing and Mike Gerholdt, Sr. Manager Admin Evangelism on an adventure with fellow Trailblazers as we discover new ways to use technology to go faster, get smarter and go further.
* Build Sophisticated App Configurations with Custom Metadata
** Overview
*** Description
At Dreamforce last year we launched custom metadata types. This year we add a heavily requested, powerful new capability: metadata relationships. You can now build complex, hierarchical metadata structures by relating your custom metadata to other custom metadata and even to standard and custom objects and fields! If you are still using custom settings or custom objects for app configurations, attend this session to learn how custom metadata types can save your time and sanity managing app configurations and eliminate the need for sophisticated custom tooling or manual configuration and deployment processes.
* Template Title
** Overview
*** Description
*** Spekaer
- hoge
- fuga
